#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace form
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="intranet2")]
	public partial class DbDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void Insertin2(in2 instance);
    partial void Updatein2(in2 instance);
    partial void Deletein2(in2 instance);
    #endregion
		
		public DbDataDataContext() : 
				base(global::form.Properties.Settings.Default.intranet2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<in2> in2
		{
			get
			{
				return this.GetTable<in2>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.in2")]
	public partial class in2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _in1num;
		
		private string _pl1no;
		
		private System.Nullable<System.DateTime> _bk1date;
		
		private string _bk1wek;
		
		private System.Nullable<decimal> _bk1cah;
		
		private System.Nullable<decimal> _bk1oth2;
		
		private System.Nullable<decimal> _bk1oth;
		
		private System.Nullable<decimal> _bk1opn;
		
		private string _bk1not;
		
		private System.Nullable<decimal> _bk1mon2;
		
		private System.Nullable<decimal> _bk1mon3;
		
		private string _pe1no;
		
		private System.Nullable<System.DateTime> _in1keyin;
		
		private System.Nullable<decimal> _bk1cash1;
		
		private System.Nullable<decimal> _bk1cash2;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onin1numChanging(decimal value);
    partial void Onin1numChanged();
    partial void Onpl1noChanging(string value);
    partial void Onpl1noChanged();
    partial void Onbk1dateChanging(System.Nullable<System.DateTime> value);
    partial void Onbk1dateChanged();
    partial void Onbk1wekChanging(string value);
    partial void Onbk1wekChanged();
    partial void Onbk1cahChanging(System.Nullable<decimal> value);
    partial void Onbk1cahChanged();
    partial void Onbk1oth2Changing(System.Nullable<decimal> value);
    partial void Onbk1oth2Changed();
    partial void Onbk1othChanging(System.Nullable<decimal> value);
    partial void Onbk1othChanged();
    partial void Onbk1opnChanging(System.Nullable<decimal> value);
    partial void Onbk1opnChanged();
    partial void Onbk1notChanging(string value);
    partial void Onbk1notChanged();
    partial void Onbk1mon2Changing(System.Nullable<decimal> value);
    partial void Onbk1mon2Changed();
    partial void Onbk1mon3Changing(System.Nullable<decimal> value);
    partial void Onbk1mon3Changed();
    partial void Onpe1noChanging(string value);
    partial void Onpe1noChanged();
    partial void Onin1keyinChanging(System.Nullable<System.DateTime> value);
    partial void Onin1keyinChanged();
    partial void Onbk1cash1Changing(System.Nullable<decimal> value);
    partial void Onbk1cash1Changed();
    partial void Onbk1cash2Changing(System.Nullable<decimal> value);
    partial void Onbk1cash2Changed();
    #endregion
		
		public in2()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_in1num", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal in1num
		{
			get
			{
				return this._in1num;
			}
			set
			{
				if ((this._in1num != value))
				{
					this.Onin1numChanging(value);
					this.SendPropertyChanging();
					this._in1num = value;
					this.SendPropertyChanged("in1num");
					this.Onin1numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pl1no", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string pl1no
		{
			get
			{
				return this._pl1no;
			}
			set
			{
				if ((this._pl1no != value))
				{
					this.Onpl1noChanging(value);
					this.SendPropertyChanging();
					this._pl1no = value;
					this.SendPropertyChanged("pl1no");
					this.Onpl1noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk1date", DbType="DateTime")]
		public System.Nullable<System.DateTime> bk1date
		{
			get
			{
				return this._bk1date;
			}
			set
			{
				if ((this._bk1date != value))
				{
					this.Onbk1dateChanging(value);
					this.SendPropertyChanging();
					this._bk1date = value;
					this.SendPropertyChanged("bk1date");
					this.Onbk1dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk1wek", DbType="Char(2)")]
		public string bk1wek
		{
			get
			{
				return this._bk1wek;
			}
			set
			{
				if ((this._bk1wek != value))
				{
					this.Onbk1wekChanging(value);
					this.SendPropertyChanging();
					this._bk1wek = value;
					this.SendPropertyChanged("bk1wek");
					this.Onbk1wekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk1cah", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> bk1cah
		{
			get
			{
				return this._bk1cah;
			}
			set
			{
				if ((this._bk1cah != value))
				{
					this.Onbk1cahChanging(value);
					this.SendPropertyChanging();
					this._bk1cah = value;
					this.SendPropertyChanged("bk1cah");
					this.Onbk1cahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk1oth2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> bk1oth2
		{
			get
			{
				return this._bk1oth2;
			}
			set
			{
				if ((this._bk1oth2 != value))
				{
					this.Onbk1oth2Changing(value);
					this.SendPropertyChanging();
					this._bk1oth2 = value;
					this.SendPropertyChanged("bk1oth2");
					this.Onbk1oth2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk1oth", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> bk1oth
		{
			get
			{
				return this._bk1oth;
			}
			set
			{
				if ((this._bk1oth != value))
				{
					this.Onbk1othChanging(value);
					this.SendPropertyChanging();
					this._bk1oth = value;
					this.SendPropertyChanged("bk1oth");
					this.Onbk1othChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk1opn", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> bk1opn
		{
			get
			{
				return this._bk1opn;
			}
			set
			{
				if ((this._bk1opn != value))
				{
					this.Onbk1opnChanging(value);
					this.SendPropertyChanging();
					this._bk1opn = value;
					this.SendPropertyChanged("bk1opn");
					this.Onbk1opnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk1not", DbType="NVarChar(MAX)")]
		public string bk1not
		{
			get
			{
				return this._bk1not;
			}
			set
			{
				if ((this._bk1not != value))
				{
					this.Onbk1notChanging(value);
					this.SendPropertyChanging();
					this._bk1not = value;
					this.SendPropertyChanged("bk1not");
					this.Onbk1notChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk1mon2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> bk1mon2
		{
			get
			{
				return this._bk1mon2;
			}
			set
			{
				if ((this._bk1mon2 != value))
				{
					this.Onbk1mon2Changing(value);
					this.SendPropertyChanging();
					this._bk1mon2 = value;
					this.SendPropertyChanged("bk1mon2");
					this.Onbk1mon2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk1mon3", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> bk1mon3
		{
			get
			{
				return this._bk1mon3;
			}
			set
			{
				if ((this._bk1mon3 != value))
				{
					this.Onbk1mon3Changing(value);
					this.SendPropertyChanging();
					this._bk1mon3 = value;
					this.SendPropertyChanged("bk1mon3");
					this.Onbk1mon3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pe1no", DbType="Char(5)")]
		public string pe1no
		{
			get
			{
				return this._pe1no;
			}
			set
			{
				if ((this._pe1no != value))
				{
					this.Onpe1noChanging(value);
					this.SendPropertyChanging();
					this._pe1no = value;
					this.SendPropertyChanged("pe1no");
					this.Onpe1noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_in1keyin", DbType="DateTime")]
		public System.Nullable<System.DateTime> in1keyin
		{
			get
			{
				return this._in1keyin;
			}
			set
			{
				if ((this._in1keyin != value))
				{
					this.Onin1keyinChanging(value);
					this.SendPropertyChanging();
					this._in1keyin = value;
					this.SendPropertyChanged("in1keyin");
					this.Onin1keyinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk1cash1", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> bk1cash1
		{
			get
			{
				return this._bk1cash1;
			}
			set
			{
				if ((this._bk1cash1 != value))
				{
					this.Onbk1cash1Changing(value);
					this.SendPropertyChanging();
					this._bk1cash1 = value;
					this.SendPropertyChanged("bk1cash1");
					this.Onbk1cash1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bk1cash2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> bk1cash2
		{
			get
			{
				return this._bk1cash2;
			}
			set
			{
				if ((this._bk1cash2 != value))
				{
					this.Onbk1cash2Changing(value);
					this.SendPropertyChanging();
					this._bk1cash2 = value;
					this.SendPropertyChanged("bk1cash2");
					this.Onbk1cash2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
